### ISSUE TITLE
Implement branch selection and loading

### ISSUE THREAD

**Issue by mattref** [jaseref/gitrospect#3]
**Backend**

- [x] #4
- [ ] #6
- [ ] Commits (_load all, per file, per branch_) #6 

**Frontend**

- [x] Load branches to "Branch Selector" (**dropdown**) #4 
- [ ] Display files in **tree view** under the "Branch Selector" #6
